const ancorsJson = [
  {
    title: "A1",
    id: 1,
    coordinate: {
      x: 300,
      y: 500,
    },
    details: [
      {
        title: "Title 1",
        power: "2.5",
        current: "5.3",
        energy: "6.8",
        date: "09/10/2020",
        active:true,
      },
      {
        title: "Title 2",
        power: "3.5",
        current: "2.3",
        energy: "7.8",
        date: "10/10/2020",
        active:true,
      },
      {
        title: "Title 3",
        power: "2.5",
        current: "5.3",
        energy: "6.8",
        date: "11/10/2020",
        active:false,
      },
      {
        title: "Title 4",
        power: "1.5",
        current: "2.3",
        energy: "3.8",
        date: "12/10/2020",
        active:false,
      },
    ],
    childs: [
      {
        title: "A1-1",
        id: 2,
        coordinate: {
          x: 320,
          y: 500,
        },
        details: [
          {
            title: "Title 1",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "09/11/2020",
            active:true,
          },
          {
            title: "Title 2",
            power: "3.5",
            current: "2.3",
            energy: "7.8",
            date: "10/11/2020",
            active:true,
          },
          {
            title: "Title 3",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "11/11/2020",
            active:false,
          },
          {
            title: "Title 4",
            power: "1.5",
            current: "2.3",
            energy: "3.8",
            date: "12/11/2020",
            active:true,
          },
        ],
      },
      {
        title: "A1-2",
        id: 3,
        coordinate: {
          x: 280,
          y: 500,
        },
        details: [
          {
            title: "Title 1",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "09/09/2020",
            active:true,
          },
          {
            title: "Title 2",
            power: "3.5",
            current: "2.3",
            energy: "7.8",
            date: "10/09/2020",
            active:true,
          },
          {
            title: "Title 3",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "11/09/2020",
            active:true,
          },
          {
            title: "Title 4",
            power: "1.5",
            current: "2.3",
            energy: "3.8",
            date: "12/09/2020",
            active:false,
          },
        ],
      },
    ],
  },
  {
    title: "B1",
    id: 4,
    coordinate: {
      x: 500,
      y: 500,
    },
    details: [
      {
        title: "Title 1",
        power: "2.5",
        current: "5.3",
        energy: "6.8",
        date: "09/01/2020",
        active:true,
      },
      {
        title: "Title 2",
        power: "3.5",
        current: "2.3",
        energy: "7.8",
        date: "10/01/2020",
        active:false,
      },
      {
        title: "Title 3",
        power: "2.5",
        current: "5.3",
        energy: "6.8",
        date: "11/01/2020",
        active:false,
      },
      {
        title: "Title 4",
        power: "1.5",
        current: "2.3",
        energy: "3.8",
        date: "12/01/2020",
        active:false,
      },
    ],
    childs: [
      {
        title: "B1-1",
        id: 5,
        coordinate: {
          x: 500,
          y: 525,
        },
        details: [
          {
            title: "Title 1",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "09/02/2020",
            active:true,
          },
          {
            title: "Title 2",
            power: "3.5",
            current: "2.3",
            energy: "7.8",
            date: "10/02/2020",
            active:true,
          },
          {
            title: "Title 3",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "11/02/2020",
            active:true,
          },
          {
            title: "Title 4",
            power: "1.5",
            current: "2.3",
            energy: "3.8",
            date: "12/02/2020",
            active:true,
          },
        ],
      },
      {
        title: "B1-2",
        id: 6,
        coordinate: {
          x: 500,
          y: 475,
        },
        details: [
          {
            title: "Title 1",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "09/03/2020",
            active:false,
          },
          {
            title: "Title 2",
            power: "3.5",
            current: "2.3",
            energy: "7.8",
            date: "10/03/2020",
            active:true,
          },
          {
            title: "Title 3",
            power: "2.5",
            current: "5.3",
            energy: "6.8",
            date: "11/03/2020",
            active:false,
          },
          {
            title: "Title 4",
            power: "1.5",
            current: "2.3",
            energy: "3.8",
            date: "12/03/2020",
            active:false,
          },
        ],
      },
    ],
  },
];

export default ancorsJson;
